### ISSUE TITLE
Question: How does the icon parameter work on MacOs?

### ISSUE THREAD

**Issue by danielbeeke** [PandawanFr/deno_notify#1]
I have used app: "firefox" with good outcomes.
I do not understand how name: [freedesktop.org name] is supposed to work.
Does that work on macOs?

Awesome library!

**Comment by PandawanFr** [comment]
Hi, I'm currently working on a documentation/platform-specific rewrite to make things easier to understand. Essentially, macOS does not really support custom icons. So what you do is you pass it the `app` option so the notification can pretend it was sent from that app.

For example, if you wanted to use the Safari icon, you'd use `{ app: "Safari" }` so the notification can pretend it was sent from Safari.

You might get good outcomes with the `name` option on other platforms, but I don't think they work on macOS. They're meant for unix notifications which might have support for icons using the names specified by freedesktop.org.

Hope that clarifies things!

**Comment by danielbeeke** [comment]
Yes it does, thank you :)
